name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'The tag for the release'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "We did the thing!"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Output Release URL File
        run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
      - name: Save Release URL File for publish
        uses: actions/upload-artifact@v1
        with:
          name: release_url
          path: release_url.txt
